---
abstract: 'MessagePack stream serializer/deserializer for AnyEvent'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-MessagePack
no_index:
  directory:
    - inc
provides:
  AnyEvent::MessagePack:
    file: lib/AnyEvent/MessagePack.pm
    version: 0.19
requires:
  AnyEvent: 7.02
  Data::MessagePack: 0.46
  Data::MessagePack::Stream: 0.07
  parent: 0
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 0.19
